/**
 * PPManticoreSDKTestDefaultSubclass.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: /Users/mmetral/dev/opensource/paypal-manticore/test/js-source/SDKTestDefault.js
 *
 * 
 */

#import "PayPalManticoreTypes.h"
#import "PPManticoreJSBackedObject.h"

@class PPManticoreSDKTest;
@class PPManticoreSDKTestDefault;
@class PPManticoreSDKTestDefaultSubclass;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * 
 */
@interface PPManticoreSDKTestDefaultSubclass : PPManticoreSDKTestDefault




/**
 * Test derived classes
 */
+(PPManticoreSDKTestDefault* _Nullable)getDerived;



/**
 * Test subclass
 */
-(BOOL)isItDerived;




@end
