/**
 * PPManticoreSDKTestDefaultSubclass.m
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: test/js-source/SDKTestDefault.js
 *
 * 
 */
#import "PayPalManticoreImports.h"
#import "PPManticoreEngine.h"
#import "PPManticoreNativeInterface.h"
#import "PPManticoreError.h"


@implementation PPManticoreSDKTestDefaultSubclass



+ (Class)nativeClassForObject:(JSValue*)value {
  if (value.isNull || value.isUndefined) {
    return self;
  }
  JSValue *nativeClass = value[@"_native"];
  if (nativeClass.isNull || nativeClass.isUndefined) {
    return self;
  }
  
  return self;
}

- (instancetype _Nullable)init {
  if ((self = [super init])) {
    self.impl = [[PPManticoreSDKTestDefaultSubclass engine] createJSObject:@"SDKTestDefaultSubclass" withArguments:nil];
  }
  return self;
}

-(BOOL)isItDerived {
    NSArray *args = nil;

    JSValue *valueToInvokeMethodOn = self.impl;
    JSValue *returnValue = [valueToInvokeMethodOn invokeMethod:@"isItDerived" withArguments:args];
    return [[PPManticoreSDKTestDefaultSubclass engine].converter toNativeBool:returnValue];
}

+(PPManticoreSDKTestDefault*)getDerived {
    NSArray *args = nil;

    JSValue *valueToInvokeMethodOn = [[PPManticoreSDKTestDefaultSubclass engine] resolveJSClass:@"SDKTestDefaultSubclass"];
    JSValue *returnValue = [valueToInvokeMethodOn invokeMethod:@"getDerived" withArguments:args];
    return [[PPManticoreSDKTestDefaultSubclass engine] attachNativeObject:returnValue ofType:[PPManticoreSDKTestDefault class]];
}



@end
